name:                hyes
version:             0.1.0.0
github:              "hygxsh2k/hyes"
license:             BSD3
author:              "hygxsh2k"
maintainer:          "hygxsh2k@gmail.com"
copyright:           "2018 hygxsh2k"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/hygxsh2k/hyes#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  hyes:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hyes
    - optparse-applicative

tests:
  hyes-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hyes
